"""
WC 2026 Monte Carlo championship probabilities — horizontal bar chart.

Reads simulation/output/wc_26_mc_title_probs.csv (generated by
simulation/monte_carlo/run.py) and shows all teams with a non-zero
probability, colour-coded by group.

Run from the project root:
    python -m viz.simulation_monte_carlo
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

OUTPUT_PATH = 'viz/output/simulation_monte_carlo.png'
INPUT_CSV   = 'simulation/output/wc_26_mc_title_probs.csv'

C_ANNOT = '#546E7A'
C_SPINE = '#CFD8DC'

# One colour per group — 12 groups, use a distinct palette
GROUP_COLORS = {
    'A': '#1F4E79',   # dark navy
    'B': '#2E75B6',   # mid blue
    'C': '#00897B',   # teal
    'D': '#6A1B9A',   # purple
    'E': '#1565C0',   # royal blue
    'F': '#2E7D32',   # dark green
    'G': '#F57F17',   # amber
    'H': '#B71C1C',   # dark red
    'I': '#00838F',   # cyan-teal
    'J': '#4527A0',   # deep purple
    'K': '#558B2F',   # olive green
    'L': '#5D4037',   # brown
}


def run():
    df = pd.read_csv(INPUT_CSV, index_col='rank')
    n_sims = df['title_count'].sum()

    # Show only teams with at least 1 title (filter out true zeros)
    df = df[df['title_count'] > 0].copy()

    # Ensure sorted by probability descending
    df = df.sort_values('title_prob', ascending=True)   # ascending for horizontal bar

    fig, ax = plt.subplots(figsize=(11, max(6, len(df) * 0.38)))
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')

    colors = [GROUP_COLORS.get(row['group'], '#90A4AE') for _, row in df.iterrows()]
    bars = ax.barh(df['team'], df['title_prob'], color=colors, height=0.7, zorder=2)

    # Value labels
    for bar, (_, row) in zip(bars, df.iterrows()):
        val = row['title_prob']
        ax.text(val + 0.002, bar.get_y() + bar.get_height() / 2,
                row['title_pct'], va='center', fontsize=8, color=C_ANNOT)

    ax.set_xlabel('Championship probability', fontsize=10, color=C_ANNOT)
    ax.set_xlim(0, df['title_prob'].max() * 1.20)
    ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.0%}'))
    ax.tick_params(axis='both', labelsize=8.5, colors=C_ANNOT)
    ax.xaxis.grid(True, color=C_SPINE, linewidth=0.6, zorder=0)
    ax.set_axisbelow(True)

    for spine in ax.spines.values():
        spine.set_edgecolor(C_SPINE)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Group legend
    present_groups = sorted(df['group'].unique())
    legend_handles = [
        mpatches.Patch(color=GROUP_COLORS[g], label=f'Group {g}')
        for g in present_groups if g in GROUP_COLORS
    ]
    ax.legend(handles=legend_handles, fontsize=7.5, loc='lower right',
              framealpha=0.9, edgecolor=C_SPINE, ncol=2)

    ax.set_title(
        f'WC 2026 — Predicted Championship Probabilities  (CatBoost · {n_sims:,} Monte Carlo simulations)',
        fontsize=12, fontweight='bold', color=C_ANNOT, pad=12,
    )

    plt.tight_layout()
    plt.savefig(OUTPUT_PATH, dpi=150, bbox_inches='tight', facecolor='white')
    print(f'Saved: {OUTPUT_PATH}')
    plt.show()


if __name__ == '__main__':
    run()
