import pandas as pd
import numpy as np
from pathlib import Path
from tqdm import tqdm


class FeaturesCreator:
    """
    Creates advanced features for soccer match prediction based on team performance metrics.
    Features are calculated for both home_team and away_team using efficient vectorized operations.

    ELO data is not loaded here — pass elo_df to create_all_features() from the pipeline.
    """

    def __init__(self, csv_path, conf_path="data/resulting_data.csv"):
        self.df = pd.read_csv(csv_path)
        self.df['date'] = pd.to_datetime(self.df['date'])
        self.df = self.df.sort_values('date').reset_index(drop=True)
        self.df_with_features = None

        # Build confederation mapping from resulting_data.csv.
        # Apply same name replacements used in db_builder.py.
        conf_df = pd.read_csv(conf_path)
        conf_df["nation_full_name"] = (
            conf_df["nation_full_name"]
            .str.replace("Czechia", "Czech Republic")
            .str.replace("IR Iran", "Iran")
            .str.replace("Korea Republic", "South Korea")
            .str.replace("USA", "United States")
            .str.replace("Bosnia-Herzegovina", "Bosnia and Herzegovina")
            .str.replace("Turkiye", "Turkey")
            .str.replace("China", "China PR", regex=False)
        )
        # Use most recent confederation per team (handles any historical changes)
        self.conf_map = (
            conf_df.sort_values('rank_date')
            .groupby('nation_full_name')['confederation']
            .last()
            .to_dict()
        )

    def calculate_points_won(self, home_score, away_score):
        """Returns points for home team: 3=win, 1=draw, 0=loss."""
        if home_score > away_score:
            return 3
        elif home_score == away_score:
            return 1
        else:
            return 0

    def _get_tournament_weight(self, tournament):
        """Weight for a match based on competition importance."""
        t = str(tournament)
        if 'FIFA World Cup' in t:
            return 1.0
        t_lower = t.lower()
        if 'qualifier' in t_lower or 'qualification' in t_lower:
            return 0.8
        if 'friendly' in t_lower:
            return 0.5
        return 0.9  # other competitive tournaments (continental cups, etc.)

    def create_all_features(self, elo_df=None, pi_df=None):
        """
        Create all features for both home and away teams.

        Args:
            elo_df: DataFrame with columns [date, home_team, away_team, home_elo, away_elo].
                    Generated by elo_calculator.py. If None, ELO features are skipped.
            pi_df:  DataFrame with columns [date, home_team, away_team,
                    pi_h_home, pi_a_home, pi_h_away, pi_a_away, pi_diff].
                    Generated by pi_ratings_calculator.py. If None, pi features are skipped.

        Returns the dataframe with all new feature columns.
        """
        df = self.df.copy()
        df = df.reset_index(drop=True)

        # ==================== BASIC POINTS ====================
        df['home_points_won'] = df.apply(
            lambda row: self.calculate_points_won(row['home_score'], row['away_score']), axis=1
        )
        df['away_points_won'] = df.apply(
            lambda row: self.calculate_points_won(row['away_score'], row['home_score']), axis=1
        )

        # ==================== TOURNAMENT WEIGHT ====================
        # Kept as a static feature only. No longer applied to weighted metrics.
        # neutral and tournament columns are carried through from the source data.
        df['tournament_weight'] = df['tournament'].apply(self._get_tournament_weight)

        # ==================== WEIGHTED POINTS (BY OPPONENT FIFA POINTS) ====================
        # Normalised by a static value (1400).
        # Results against stronger opponents earn proportionally more credit.
        norm_val = 1400.0
        df['home_points_weighted'] = df['home_points_won'] * (df['points_away'] / norm_val)
        df['away_points_weighted'] = df['away_points_won'] * (df['points_home'] / norm_val)

        # ==================== POINTS DIFFERENCE ====================
        # Positive = home team is stronger (more FIFA points). Replaces rank_dif.
        df['points_dif'] = df['points_home'] - df['points_away']

        # ==================== ELO FEATURES ====================
        if elo_df is not None:
            elo_df = elo_df.copy()
            elo_df['date'] = pd.to_datetime(elo_df['date'])
            df = df.merge(
                elo_df[['date', 'home_team', 'away_team', 'home_elo', 'away_elo']],
                on=['date', 'home_team', 'away_team'],
                how='left'
            )
            df['elo_diff'] = df['home_elo'] - df['away_elo']

        # ==================== PI-RATINGS ====================
        if pi_df is not None:
            pi_df = pi_df.copy()
            pi_df['date'] = pd.to_datetime(pi_df['date'])
            df = df.merge(
                pi_df[['date', 'home_team', 'away_team',
                        'pi_h_home', 'pi_a_home', 'pi_h_away', 'pi_a_away', 'pi_diff']],
                on=['date', 'home_team', 'away_team'],
                how='left'
            )

        # ==================== CONFEDERATION ====================
        df['confederation_home'] = df['home_team'].map(self.conf_map)
        df['confederation_away'] = df['away_team'].map(self.conf_map)

        # ==================== ROLLING / MOVING AVERAGE FEATURES ====================
        print("Calculating moving averages...")
        df = self._add_all_moving_averages_efficient(df)

        self.df_with_features = df
        return df

    def _add_all_moving_averages_efficient(self, df):
        """
        Calculate all rolling features for home and away teams.
        Uses only games strictly before the match date (no leakage).
        """
        features_list = []

        for _, row in tqdm(df.iterrows(), total=len(df), desc='Moving averages', unit='match'):
            home_features = self._calculate_team_features_at_date(df, row['home_team'], row['date'])
            away_features = self._calculate_team_features_at_date(df, row['away_team'], row['date'])

            row_features = {}
            for key, val in home_features.items():
                row_features[f'home_{key}'] = val
            for key, val in away_features.items():
                row_features[f'away_{key}'] = val

            features_list.append(row_features)

        features_df = pd.DataFrame(features_list)
        df = pd.concat([df, features_df], axis=1)
        return df

    def _calculate_team_features_at_date(self, df, team, current_date):
        """
        Calculate all rolling features for a team using only games before current_date.
        Returns a dict with feature keys (without team prefix).
        """
        team_games = self._get_team_games_before_date(df, team, current_date)
        features = {}

        nan_features = [
            'points_won_ma_20', 'points_won_ma_10', 'points_won_ma_5', 'points_won_ma_3',
            'points_weighted_ma_20', 'points_weighted_ma_10', 'points_weighted_ma_5', 'points_weighted_ma_3',
            'goals_ma_20', 'goals_ma_10', 'goals_ma_5', 'goals_ma_3',
            'goals_suffered_ma_20', 'goals_suffered_ma_10', 'goals_suffered_ma_5', 'goals_suffered_ma_3',
            'goals_weighted_ma_20', 'goals_weighted_ma_10', 'goals_weighted_ma_5', 'goals_weighted_ma_3',
            'goals_suffered_weighted_ma_20', 'goals_suffered_weighted_ma_10', 'goals_suffered_weighted_ma_5', 'goals_suffered_weighted_ma_3',
            'goal_diff_ma_20', 'goal_diff_ma_10', 'goal_diff_ma_5', 'goal_diff_ma_3',
            'form_trend_5', 'form_trend_3',
            'days_since_last_match',
        ]

        if len(team_games) == 0:
            for feat in nan_features:
                features[feat] = np.nan
            return features

        points_won = team_games['points_won'].values
        points_weighted = team_games['points_weighted'].values
        goals = team_games['goals'].values
        goals_suffered = team_games['goals_suffered'].values
        goals_weighted = team_games['goals_weighted'].values
        goals_suffered_weighted = team_games['goals_suffered_weighted'].values
        goal_diff = team_games['goal_diff'].values

        # Moving averages — last 20, 10, 5 and last 3 games
        windows = [20, 10, 5, 3]
        for w in windows:
            features[f'points_won_ma_{w}'] = np.mean(points_won[-w:])
            features[f'points_weighted_ma_{w}'] = np.mean(points_weighted[-w:])
            features[f'goals_ma_{w}'] = np.mean(goals[-w:])
            features[f'goals_suffered_ma_{w}'] = np.mean(goals_suffered[-w:])
            features[f'goals_weighted_ma_{w}'] = np.mean(goals_weighted[-w:])
            features[f'goals_suffered_weighted_ma_{w}'] = np.mean(goals_suffered_weighted[-w:])
            features[f'goal_diff_ma_{w}'] = np.mean(goal_diff[-w:])

        # Form trend — linear slope of points_won over recent games.
        # Positive = improving, negative = declining.
        # Captures trajectory: a team winning after a slump differs from one declining after
        # a hot streak, even when their MA5 is identical.
        for window, key in [(5, 'form_trend_5'), (3, 'form_trend_3')]:
            arr = points_won[-window:]
            n = len(arr)
            features[key] = np.polyfit(range(n), arr, 1)[0] if n >= 2 else np.nan

        # Days since last match — captures fatigue and match rhythm
        features['days_since_last_match'] = (current_date - team_games['date'].iloc[-1]).days

        return features

    def _get_team_games_before_date(self, df, team, current_date):
        """
        Get all games for a team before current_date with computed per-game metrics.

        Weighting logic:
          - goals_weighted: multiplied by (opponent_points / 1400) — scoring vs stronger teams counts more
          - goals_suffered_weighted: divided by (opponent_points / 1400) — conceding vs stronger teams counts less
        """
        keep_cols = ['date', 'points_won', 'points_weighted', 'goals', 'goals_suffered',
                     'goals_weighted', 'goals_suffered_weighted', 'goal_diff']

        norm_val = 1400.0

        # Home games (team is home, opponent is away)
        home = df[(df['home_team'] == team) & (df['date'] < current_date)].copy()
        home['points_won'] = home.apply(
            lambda r: self.calculate_points_won(r['home_score'], r['away_score']), axis=1
        )
        home['points_weighted'] = home['points_won'] * (home['points_away'] / norm_val)
        home['goals'] = home['home_score']
        home['goals_suffered'] = home['away_score']
        # Goals scored weighted UP by opponent strength — scoring vs strong teams is worth more
        home['goals_weighted'] = home['goals'] * (home['points_away'] / norm_val)
        # Goals conceded weighted DOWN by opponent strength — conceding vs strong teams is less bad
        home['goals_suffered_weighted'] = home['goals_suffered'] / (home['points_away'] / norm_val)
        home['goal_diff'] = home['goals'] - home['goals_suffered']

        # Away games (team is away, opponent is home)
        away = df[(df['away_team'] == team) & (df['date'] < current_date)].copy()
        away['points_won'] = away.apply(
            lambda r: self.calculate_points_won(r['away_score'], r['home_score']), axis=1
        )
        away['points_weighted'] = away['points_won'] * (away['points_home'] / norm_val)
        away['goals'] = away['away_score']
        away['goals_suffered'] = away['home_score']
        # Goals scored weighted UP by opponent strength
        away['goals_weighted'] = away['goals'] * (away['points_home'] / norm_val)
        # Goals conceded weighted DOWN by opponent strength
        away['goals_suffered_weighted'] = away['goals_suffered'] / (away['points_home'] / norm_val)
        away['goal_diff'] = away['goals'] - away['goals_suffered']

        team_games = pd.concat([home[keep_cols], away[keep_cols]], ignore_index=True)
        team_games = team_games.sort_values('date').reset_index(drop=True)
        return team_games

    def save_to_csv(self, output_path):
        """Save the features dataframe to CSV."""
        self.df_with_features.to_csv(output_path, index=False)
        print(f"Features saved to {output_path}")

    def get_features_dataframe(self):
        """Return the dataframe with all features."""
        return self.df_with_features
