import pandas as pd
import numpy as np
from pathlib import Path
from tqdm import tqdm


class FeaturesCreator:
    """
    Creates advanced features for soccer match prediction based on team performance metrics.
    Features are calculated for both home_team and away_team using efficient vectorized operations.

    ELO data is not loaded here — pass elo_df to create_all_features() from the pipeline.
    """

    def __init__(self, csv_path, conf_path="data/resulting_data.csv"):
        self.df = pd.read_csv(csv_path)
        self.df['date'] = pd.to_datetime(self.df['date'])
        self.df = self.df.sort_values('date').reset_index(drop=True)
        self.df_with_features = None

        # Build confederation mapping from resulting_data.csv.
        # Apply same name replacements used in db_builder.py.
        conf_df = pd.read_csv(conf_path)
        conf_df["nation_full_name"] = (
            conf_df["nation_full_name"]
            .str.replace("Czechia", "Czech Republic")
            .str.replace("IR Iran", "Iran")
            .str.replace("Korea Republic", "South Korea")
            .str.replace("USA", "United States")
            .str.replace("Bosnia-Herzegovina", "Bosnia and Herzegovina")
            .str.replace("Turkiye", "Turkey")
            .str.replace("China", "China PR", regex=False)
            .str.replace("Democratic Republic of the Congo", "DR Congo", regex=False)
        )
        # Use most recent confederation per team (handles any historical changes)
        self.conf_map = (
            conf_df.sort_values('rank_date')
            .groupby('nation_full_name')['confederation']
            .last()
            .to_dict()
        )

    def calculate_points_won(self, home_score, away_score):
        """Returns points for home team: 3=win, 1=draw, 0=loss. NaN for unknown results."""
        if pd.isna(home_score) or pd.isna(away_score):
            return np.nan
        if home_score > away_score:
            return 3
        elif home_score == away_score:
            return 1
        else:
            return 0

    def _get_tournament_weight(self, tournament):
        """Weight for a match based on competition importance."""
        t = str(tournament)
        if 'FIFA World Cup' in t:
            return 1.0
        t_lower = t.lower()
        if 'qualifier' in t_lower or 'qualification' in t_lower:
            return 0.8
        if 'friendly' in t_lower:
            return 0.5
        return 0.9  # other competitive tournaments (continental cups, etc.)

    def create_all_features(self, elo_df=None, pi_df=None):
        """
        Create all features for both home and away teams.

        Args:
            elo_df: DataFrame with columns [date, home_team, away_team, home_elo, away_elo].
                    Generated by elo_calculator.py. If None, ELO features are skipped.
            pi_df:  DataFrame with columns [date, home_team, away_team,
                    pi_h_home, pi_a_home, pi_h_away, pi_a_away, pi_diff].
                    Generated by pi_ratings_calculator.py. If None, pi features are skipped.

        Returns the dataframe with all new feature columns.
        """
        df = self.df.copy()
        df = df.reset_index(drop=True)

        # ==================== BASIC POINTS ====================
        df['home_points_won'] = df.apply(
            lambda row: self.calculate_points_won(row['home_score'], row['away_score']), axis=1
        )
        df['away_points_won'] = df.apply(
            lambda row: self.calculate_points_won(row['away_score'], row['home_score']), axis=1
        )

        # ==================== TOURNAMENT WEIGHT ====================
        # Kept as a static feature only. No longer applied to weighted metrics.
        # neutral and tournament columns are carried through from the source data.
        df['tournament_weight'] = df['tournament'].apply(self._get_tournament_weight)

        # Ensure points columns are numeric (CSV may have mixed types from merge)
        df['points_home'] = pd.to_numeric(df['points_home'], errors='coerce')
        df['points_away'] = pd.to_numeric(df['points_away'], errors='coerce')

        # ==================== WEIGHTED POINTS (BY OPPONENT FIFA POINTS) ====================
        # Normalised by a static value (1400).
        # Results against stronger opponents earn proportionally more credit.
        norm_val = 1400.0
        df['home_points_weighted'] = df['home_points_won'] * (df['points_away'] / norm_val)
        df['away_points_weighted'] = df['away_points_won'] * (df['points_home'] / norm_val)

        # ==================== POINTS DIFFERENCE ====================
        # Positive = home team is stronger (more FIFA points). Replaces rank_dif.
        df['points_dif'] = df['points_home'] - df['points_away']

        # ==================== ELO FEATURES ====================
        if elo_df is not None:
            elo_df = elo_df.copy()
            elo_df['date'] = pd.to_datetime(elo_df['date'])
            df = df.merge(
                elo_df[['date', 'home_team', 'away_team', 'home_elo', 'away_elo']],
                on=['date', 'home_team', 'away_team'],
                how='left'
            )
            df['elo_diff'] = df['home_elo'] - df['away_elo']

            # ── ELO momentum + historical peak/low ────────────────────────────
            # Build a per-team ELO time series from the match-level ELO file.
            # Each row in elo_df is the pre-match ELO (known before kickoff → no leakage).
            elo_h = elo_df[['date', 'home_team', 'home_elo']].rename(
                columns={'home_team': 'team', 'home_elo': 'elo'})
            elo_a = elo_df[['date', 'away_team', 'away_elo']].rename(
                columns={'away_team': 'team', 'away_elo': 'elo'})
            elo_long = (
                pd.concat([elo_h, elo_a], ignore_index=True)
                .drop_duplicates(subset=['team', 'date'], keep='last')
                .sort_values(['team', 'date'])
                .reset_index(drop=True)
            )

            elo_feat_parts = []
            for team, grp in elo_long.groupby('team', sort=False):
                grp = grp.set_index('date').sort_index()
                # Rolling mean ELO at multiple time horizons
                grp['elo_ma_2yr'] = grp['elo'].rolling('730D',  min_periods=1).mean()
                grp['elo_ma_4yr'] = grp['elo'].rolling('1461D', min_periods=1).mean()
                grp['elo_ma_8yr'] = grp['elo'].rolling('2922D', min_periods=1).mean()
                grp = grp.reset_index()
                # Game-count momentum: ELO change over last 20 matches
                grp['elo_delta_20'] = grp['elo'] - grp['elo'].shift(20)
                elo_feat_parts.append(grp[['date', 'team',
                                           'elo_delta_20',
                                           'elo_ma_2yr', 'elo_ma_4yr', 'elo_ma_8yr']])

            elo_long_feats = pd.concat(elo_feat_parts, ignore_index=True)

            elo_cols = ['elo_delta_20', 'elo_ma_2yr', 'elo_ma_4yr', 'elo_ma_8yr']
            df = df.merge(
                elo_long_feats.rename(columns={'team': 'home_team'} |
                                      {c: f'home_{c}' for c in elo_cols}),
                on=['date', 'home_team'], how='left'
            )
            df = df.merge(
                elo_long_feats.rename(columns={'team': 'away_team'} |
                                      {c: f'away_{c}' for c in elo_cols}),
                on=['date', 'away_team'], how='left'
            )

            # ── Year-end ELO averages ─────────────────────────────────────────
            # For each team, take the last ELO observation in each calendar year
            # and compute the rolling average over the previous 10 / 20 years.
            # shift(1) ensures only PAST year-end values are used (no leakage).
            elo_long['year'] = elo_long['date'].dt.year
            year_end = (
                elo_long.sort_values('date')
                .groupby(['team', 'year'])['elo']
                .last()
                .reset_index()
            )
            avg_elo_parts = []
            for team, grp in year_end.groupby('team'):
                grp = grp.sort_values('year').reset_index(drop=True)
                grp['avg_elo_10yr'] = grp['elo'].rolling(10, min_periods=1).mean().shift(1)
                grp['avg_elo_20yr'] = grp['elo'].rolling(20, min_periods=1).mean().shift(1)
                avg_elo_parts.append(grp[['team', 'year', 'avg_elo_10yr', 'avg_elo_20yr']])
            avg_elo_year = pd.concat(avg_elo_parts, ignore_index=True)

            df['_year'] = df['date'].dt.year
            df = df.merge(
                avg_elo_year.rename(columns={
                    'team': 'home_team',
                    'avg_elo_10yr': 'home_avg_elo_10yr',
                    'avg_elo_20yr': 'home_avg_elo_20yr',
                })[['home_team', 'year', 'home_avg_elo_10yr', 'home_avg_elo_20yr']],
                left_on=['home_team', '_year'], right_on=['home_team', 'year'], how='left'
            ).drop(columns='year', errors='ignore')
            df = df.merge(
                avg_elo_year.rename(columns={
                    'team': 'away_team',
                    'avg_elo_10yr': 'away_avg_elo_10yr',
                    'avg_elo_20yr': 'away_avg_elo_20yr',
                })[['away_team', 'year', 'away_avg_elo_10yr', 'away_avg_elo_20yr']],
                left_on=['away_team', '_year'], right_on=['away_team', 'year'], how='left'
            ).drop(columns=['year', '_year'], errors='ignore')

        # ==================== PI-RATINGS ====================
        if pi_df is not None:
            pi_df = pi_df.copy()
            pi_df['date'] = pd.to_datetime(pi_df['date'])
            df = df.merge(
                pi_df[['date', 'home_team', 'away_team',
                        'pi_h_home', 'pi_a_home', 'pi_h_away', 'pi_a_away', 'pi_diff']],
                on=['date', 'home_team', 'away_team'],
                how='left'
            )

        # ==================== CONFEDERATION ====================
        df['confederation_home'] = df['home_team'].map(self.conf_map)
        df['confederation_away'] = df['away_team'].map(self.conf_map)

        # ==================== WC HISTORY STATS ====================
        # Total WC games played and goals scored per team across all history.
        # Computed from the full international_results.csv — static lookup, not rolling.
        wc_df = pd.read_csv('data/international_results.csv')
        wc_df = wc_df[wc_df['tournament'] == 'FIFA World Cup'].dropna(
            subset=['home_score', 'away_score'])
        # Apply same name normalisations used in the ranked database
        for col in ['home_team', 'away_team']:
            wc_df[col] = (wc_df[col]
                .str.replace('IR Iran',                          'Iran',                  regex=False)
                .str.replace('Korea Republic',                   'South Korea',           regex=False)
                .str.replace('USA',                              'United States',         regex=False)
                .str.replace('Bosnia-Herzegovina',               'Bosnia and Herzegovina',regex=False)
                .str.replace('Turkiye',                          'Turkey',                regex=False)
                .str.replace('Democratic Republic of the Congo', 'DR Congo',              regex=False)
                .str.replace('Czechia',                          'Czech Republic',        regex=False)
            )
            wc_df[col] = wc_df[col].str.replace('China(?! PR)', 'China PR', regex=True)

        teams = set(wc_df['home_team']) | set(wc_df['away_team'])
        wc_games = {}
        wc_goals = {}
        wc_goals_conceded = {}
        for team in teams:
            h = wc_df[wc_df['home_team'] == team]
            a = wc_df[wc_df['away_team'] == team]
            wc_games[team]          = len(h) + len(a)
            wc_goals[team]          = int(h['home_score'].sum() + a['away_score'].sum())
            wc_goals_conceded[team] = int(h['away_score'].sum() + a['home_score'].sum())

        # Per-game rates — 0 for teams that never qualified
        wc_gpg  = {t: wc_goals[t]          / wc_games[t] if wc_games[t] > 0 else 0.0 for t in teams}
        wc_gcpg = {t: wc_goals_conceded[t] / wc_games[t] if wc_games[t] > 0 else 0.0 for t in teams}

        df['home_wc_games'] = df['home_team'].map(wc_games).fillna(0).astype(int)
        df['home_wc_goals'] = df['home_team'].map(wc_goals).fillna(0).astype(int)
        df['away_wc_games'] = df['away_team'].map(wc_games).fillna(0).astype(int)
        df['away_wc_goals'] = df['away_team'].map(wc_goals).fillna(0).astype(int)

        df['home_wc_goals_per_game']          = df['home_team'].map(wc_gpg).fillna(0)
        df['home_wc_goals_conceded_per_game'] = df['home_team'].map(wc_gcpg).fillna(0)
        df['away_wc_goals_per_game']          = df['away_team'].map(wc_gpg).fillna(0)
        df['away_wc_goals_conceded_per_game'] = df['away_team'].map(wc_gcpg).fillna(0)

        # Best WC round ever reached per team
        # 0=never qualified, 1=group stage, 2=R16, 3=QF, 4=SF, 5=Final/3rd, 6=Champion
        wc_best_round = self._compute_wc_best_round(wc_df)
        df['home_wc_best_round'] = df['home_team'].map(wc_best_round).fillna(0).astype(int)
        df['away_wc_best_round'] = df['away_team'].map(wc_best_round).fillna(0).astype(int)

        # ==================== ROLLING / MOVING AVERAGE FEATURES ====================
        print("Calculating moving averages...")
        df = self._add_all_moving_averages_efficient(df)

        self.df_with_features = df
        return df

    def _add_all_moving_averages_efficient(self, df):
        """
        Calculate all rolling features for home and away teams.
        Uses only games strictly before the match date (no leakage).
        """
        features_list = []

        for _, row in tqdm(df.iterrows(), total=len(df), desc='Moving averages', unit='match'):
            home_features = self._calculate_team_features_at_date(df, row['home_team'], row['date'])
            away_features = self._calculate_team_features_at_date(df, row['away_team'], row['date'])

            row_features = {}
            for key, val in home_features.items():
                row_features[f'home_{key}'] = val
            for key, val in away_features.items():
                row_features[f'away_{key}'] = val

            features_list.append(row_features)

        features_df = pd.DataFrame(features_list)
        df = pd.concat([df, features_df], axis=1)
        return df

    def _calculate_team_features_at_date(self, df, team, current_date):
        """
        Calculate all rolling features for a team using only games before current_date.
        Returns a dict with feature keys (without team prefix).
        """
        team_games = self._get_team_games_before_date(df, team, current_date)
        features = {}

        nan_features = [
            'points_won_ma_20', 'points_won_ma_10', 'points_won_ma_5', 'points_won_ma_3',
            'points_weighted_ma_20', 'points_weighted_ma_10', 'points_weighted_ma_5', 'points_weighted_ma_3',
            'goals_ma_20', 'goals_ma_10', 'goals_ma_5', 'goals_ma_3',
            'goals_suffered_ma_20', 'goals_suffered_ma_10', 'goals_suffered_ma_5', 'goals_suffered_ma_3',
            'goals_weighted_ma_20', 'goals_weighted_ma_10', 'goals_weighted_ma_5', 'goals_weighted_ma_3',
            'goals_suffered_weighted_ma_20', 'goals_suffered_weighted_ma_10', 'goals_suffered_weighted_ma_5', 'goals_suffered_weighted_ma_3',
            'goal_diff_ma_20', 'goal_diff_ma_10', 'goal_diff_ma_5', 'goal_diff_ma_3',
            'form_trend_5', 'form_trend_3',
            'days_since_last_match',
        ]

        if len(team_games) == 0:
            for feat in nan_features:
                features[feat] = np.nan
            return features

        points_won = team_games['points_won'].values
        points_weighted = team_games['points_weighted'].values
        goals = team_games['goals'].values
        goals_suffered = team_games['goals_suffered'].values
        goals_weighted = team_games['goals_weighted'].values
        goals_suffered_weighted = team_games['goals_suffered_weighted'].values
        goal_diff = team_games['goal_diff'].values

        # Moving averages — last 20, 10, 5 and last 3 games
        windows = [20, 10, 5, 3]
        for w in windows:
            features[f'points_won_ma_{w}'] = np.mean(points_won[-w:])
            features[f'points_weighted_ma_{w}'] = np.mean(points_weighted[-w:])
            features[f'goals_ma_{w}'] = np.mean(goals[-w:])
            features[f'goals_suffered_ma_{w}'] = np.mean(goals_suffered[-w:])
            features[f'goals_weighted_ma_{w}'] = np.mean(goals_weighted[-w:])
            features[f'goals_suffered_weighted_ma_{w}'] = np.mean(goals_suffered_weighted[-w:])
            features[f'goal_diff_ma_{w}'] = np.mean(goal_diff[-w:])

        # Form trend — linear slope of points_won over recent games.
        # Positive = improving, negative = declining.
        # Captures trajectory: a team winning after a slump differs from one declining after
        # a hot streak, even when their MA5 is identical.
        for window, key in [(5, 'form_trend_5'), (3, 'form_trend_3')]:
            arr = points_won[-window:]
            n = len(arr)
            features[key] = np.polyfit(range(n), arr, 1)[0] if n >= 2 else np.nan

        # Days since last match — captures fatigue and match rhythm
        features['days_since_last_match'] = (current_date - team_games['date'].iloc[-1]).days

        return features

    def _get_team_games_before_date(self, df, team, current_date):
        """
        Get all games for a team before current_date with computed per-game metrics.

        Weighting logic:
          - goals_weighted: multiplied by (opponent_points / 1400) — scoring vs stronger teams counts more
          - goals_suffered_weighted: divided by (opponent_points / 1400) — conceding vs stronger teams counts less
        """
        keep_cols = ['date', 'points_won', 'points_weighted', 'goals', 'goals_suffered',
                     'goals_weighted', 'goals_suffered_weighted', 'goal_diff']

        norm_val = 1400.0

        # Home games (team is home, opponent is away) — exclude rows with unknown scores (future matches)
        home = df[(df['home_team'] == team) & (df['date'] < current_date) & df['home_score'].notna()].copy()
        home['points_won'] = home.apply(
            lambda r: self.calculate_points_won(r['home_score'], r['away_score']), axis=1
        )
        home['points_weighted'] = home['points_won'] * (home['points_away'] / norm_val)
        home['goals'] = home['home_score']
        home['goals_suffered'] = home['away_score']
        # Goals scored weighted UP by opponent strength — scoring vs strong teams is worth more
        home['goals_weighted'] = home['goals'] * (home['points_away'] / norm_val)
        # Goals conceded weighted DOWN by opponent strength — conceding vs strong teams is less bad
        home['goals_suffered_weighted'] = home['goals_suffered'] / (home['points_away'] / norm_val)
        home['goal_diff'] = home['goals'] - home['goals_suffered']

        # Away games (team is away, opponent is home) — exclude rows with unknown scores (future matches)
        away = df[(df['away_team'] == team) & (df['date'] < current_date) & df['away_score'].notna()].copy()
        away['points_won'] = away.apply(
            lambda r: self.calculate_points_won(r['away_score'], r['home_score']), axis=1
        )
        away['points_weighted'] = away['points_won'] * (away['points_home'] / norm_val)
        away['goals'] = away['away_score']
        away['goals_suffered'] = away['home_score']
        # Goals scored weighted UP by opponent strength
        away['goals_weighted'] = away['goals'] * (away['points_home'] / norm_val)
        # Goals conceded weighted DOWN by opponent strength
        away['goals_suffered_weighted'] = away['goals_suffered'] / (away['points_home'] / norm_val)
        away['goal_diff'] = away['goals'] - away['goals_suffered']

        team_games = pd.concat([home[keep_cols], away[keep_cols]], ignore_index=True)
        team_games = team_games.sort_values('date').reset_index(drop=True)
        return team_games

    def save_to_csv(self, output_path):
        """Save the features dataframe to CSV."""
        self.df_with_features.to_csv(output_path, index=False)
        print(f"Features saved to {output_path}")

    def get_features_dataframe(self):
        """Return the dataframe with all features."""
        return self.df_with_features

    def _compute_wc_best_round(self, wc_df):
        """
        Best WC round ever reached per team across all historical editions.

        Round encoding: 0=never qualified, 1=group stage, 2=R16, 3=QF,
                        4=SF, 5=Final or 3rd-place, 6=Champion.

        Covers 1986–2022 (R16-era). Knockout rounds are inferred from
        consecutive date clusters within each edition — no round column needed.
        """
        wc_df = wc_df.copy()
        wc_df['date'] = pd.to_datetime(wc_df['date'])
        wc_df['year'] = wc_df['date'].dt.year
        wc_df = wc_df.sort_values('date')

        # First date of the knockout phase for each WC edition.
        WC_KO_START = {
            2022: pd.Timestamp('2022-12-03'),
            2018: pd.Timestamp('2018-06-30'),
            2014: pd.Timestamp('2014-06-28'),
            2010: pd.Timestamp('2010-06-26'),
            2006: pd.Timestamp('2006-06-24'),
            2002: pd.Timestamp('2002-06-15'),
            1998: pd.Timestamp('1998-06-27'),
            1994: pd.Timestamp('1994-06-25'),
            1990: pd.Timestamp('1990-06-23'),
            1986: pd.Timestamp('1986-06-15'),
        }

        best_round = {}

        for year, ko_start in WC_KO_START.items():
            yr_df = wc_df[wc_df['year'] == year].sort_values('date')
            if len(yr_df) == 0:
                continue

            # Every team that appeared gets at least group stage (1)
            for team in set(yr_df['home_team']) | set(yr_df['away_team']):
                best_round[team] = max(best_round.get(team, 0), 1)

            ko_df = yr_df[yr_df['date'] >= ko_start]
            if len(ko_df) == 0:
                continue

            # Cluster consecutive knockout dates (≤1 day apart) → rounds
            ko_dates = sorted(ko_df['date'].unique())
            round_groups = []
            current = [ko_dates[0]]
            for d in ko_dates[1:]:
                if (d - current[-1]).days <= 1:
                    current.append(d)
                else:
                    round_groups.append(current)
                    current = [d]
            round_groups.append(current)
            # round_groups[0]=R16(2), [1]=QF(3), [2]=SF(4), [3]=3rd+Final(5)

            for ri, date_grp in enumerate(round_groups):
                round_score = min(ri + 2, 5)
                for _, match in ko_df[ko_df['date'].isin(date_grp)].iterrows():
                    for team in [match['home_team'], match['away_team']]:
                        best_round[team] = max(best_round.get(team, 0), round_score)

            # Champion: winner of last match in the edition (the Final)
            final = yr_df.iloc[-1]
            if final['home_score'] > final['away_score']:
                best_round[final['home_team']] = max(best_round.get(final['home_team'], 0), 6)
            elif final['away_score'] > final['home_score']:
                best_round[final['away_team']] = max(best_round.get(final['away_team'], 0), 6)

        return best_round
